### ISSUE TITLE
Unable to load plugin when running inside of docker container.

### ISSUE THREAD

**Issue by timuckun** [GoogleCloudPlatform/fluent-plugin-google-cloud#264]
Is there a sample app or config file or some documentation anywhere on the internet to make this work with fluentd. None of the web pages I have visited resulted in a working environment.

Dockerfile

```bash
FROM fluent/fluentd:v1.2.6-onbuild

RUN apk add --update --virtual .build-deps \
        sudo build-base ruby-dev \
 # cutomize following instruction as you wish
 && sudo gem install  fluent-plugin-secure-forward \
 && sudo gem install fluent-plugin-elasticsearch \
 && sudo gem install fluent-plugin-google-cloud \
 && sudo gem sources --clear-all \
 && apk del .build-deps \
 && rm -rf /var/cache/apk/* \
           /home/fluent/.gem/ruby/2.3.0/cache/*.gem

EXPOSE 24284
```
fluent.conf

This works

```bash

<source>
  @type forward
  port 24224
  bind 0.0.0.0
</source>
<match *.**>
  @type copy

  <store>
    @type stdout
  </store>
</match>

```

This doesn't work and gives the error below

```bash
<source>
  @type forward
  port 24224
  bind 0.0.0.0
</source>
<match **>
  @type google_cloud
</match>
```

docker-compose.yml
```yaml
services:
  keycloak:
    container_name: keycloak_server
    image: jboss/keycloak
    ports:
     - 8443:8443
      - 8080:8080
    env_file:
        - .env_development
    links:
        - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access

  fluentd:
    build: ./fluentd
    container_name: fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    ports:
      - "24224:24224"
      - "24224:24224/udp"

```
Error Message

```bash
Recreating fluentd ... done
Recreating keycloak_server ... done
Attaching to fluentd, keycloak_server
fluentd     | 2018-10-29 00:54:50 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/fluent.conf"
fluentd     | /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- /usr/lib/ruby/gems/2.4.0/gems/fluent-plugin-google-cloud-0.7.0/lib/fluent/plugin/out_google_cloud (LoadError)
fluentd     | 	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
fluentd     | 	from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/lib/fluent/registry.rb:102:in `block in search'
fluentd     | 	from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/lib/fluent/registry.rb:99:in `each'
fluentd     | 	from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/lib/fluent/registry.rb:99:in `search'
fluentd     | 	from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/lib/fluent/registry.rb:44:in `lookup'
fluentd     | 	from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/lib/fluent/plugin.rb:146:in `new_impl'
fluentd     | 	from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/lib/fluent/plugin.rb:104:in `new_output'
fluentd     | 	from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/lib/fluent/agent.rb:128:in `add_match'
fluentd     | 	from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/lib/fluent/agent.rb:72:in `block in configure'
fluentd     | 	from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/lib/fluent/agent.rb:64:in `each'
fluentd     | 	from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/lib/fluent/agent.rb:64:in `configure'
fluentd     | 	from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/lib/fluent/root_agent.rb:112:in `configure'
fluentd     | 	from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/lib/fluent/engine.rb:131:in `configure'
fluentd     | 	from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/lib/fluent/engine.rb:96:in `run_configure'
fluentd     | 	from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/lib/fluent/supervisor.rb:795:in `run_configure'
fluentd     | 	from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/lib/fluent/supervisor.rb:579:in `dry_run'
fluentd     | 	from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/lib/fluent/supervisor.rb:597:in `supervise'
fluentd     | 	from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/lib/fluent/supervisor.rb:502:in `run_supervisor'
fluentd     | 	from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/lib/fluent/command/fluentd.rb:310:in `<top (required)>'
fluentd     | 	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
fluentd     | 	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
fluentd     | 	from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/bin/fluentd:8:in `<top (required)>'
fluentd     | 	from /usr/bin/fluentd:23:in `load'
fluentd     | 	from /usr/bin/fluentd:23:in `<main>'
keycloak_server | WARNING: no logs are available with the 'fluentd' log driver

```
