### ISSUE TITLE
Dropping 2 log message(s) error="User unauthorized to access

### ISSUE THREAD

**Issue by letusfly85** [GoogleCloudPlatform/fluent-plugin-google-cloud#295]
The environment is the following.

What does `User unauthorized` mean?

I use a service account json file, it includes enough permissions.

- https://cloud.google.com/monitoring/agent/install-agent?&_ga=2.63513450.-4587457.1550637762#create-private-key

### settings

```yaml
version: "3.3"

services:
  front:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    logging:
      driver: "fluentd"
      options:
          fluentd-address: "0.0.0.0:24224"
          tag: "docker.{{.FullID}}"
          fluentd-async-connect: "true"
  logger:
    &default-logging
    image: local/fluentd  # including fluent-plugin-google-cloud gem
    container_name: fluentd
    volumes:
      - ./fluentd/etc:/fluentd/etc
      - ./fluentd/auth:/etc/google/auth
    environment:
            - APPLICATION_DEFAULT_CREDS="/etc/google/auth/application_default_credentials.json"
    links:
      - front
    ports:
      - 127.0.0.1:24224:24224
```

```
<source>
  @type forward
  port 24224
  bind 0.0.0.0
</source>
<filter **>
  @type add_insert_ids
</filter>
<match **>
  @type google_cloud
</match>
```

### errors

- I start up containers, and after a few seconds later, access to the nginx by `curl` 
- And I got errors like below. (`**********` is masked.)

```bash
fluentd   | 2019-02-20 08:37:09 +0000 [warn]: #0 Dropping 2 log message(s) error="User unauthorized to access **********" error_code="7"
```
