### ISSUE TITLE
High memory consumtion

### ISSUE THREAD

**Issue by Crassirostris** [GoogleCloudPlatform/fluent-plugin-google-cloud#87]
@piosz

This issue is strongly connected to google cloud plugin usage in Kubernetes and following problems:
- https://github.com/kubernetes/kubernetes/issues/32762
- https://github.com/kubernetes/kubernetes/issues/29411
- https://github.com/kubernetes/kubernetes/issues/23782

Basically, the problem is when fluentd with google cloud plugin starts to experience some load, memory consumption starts to grow and after some time (minutes, sometimes seconds) it exceeds it's limits (currently, 200 Mb) and fluentd crashes. It can result in data losses and sometimes even prevent logs to be delivered at all, when fluentd enters infinite crash loop.

[Kubernetes fluentd configuration](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-gcp/fluentd-gcp-image/google-fluentd-journal.conf)
## How to reproduce

We can reproduce it within kubernetes cluster, starting pod with this specs

```
apiVersion: v1
kind: Pod
metadata:
  name: logs-generator-pod
spec:
  containers:
  - name: logs-generator-cont
    image: gcr.io/google_containers/logs-generator
    env:
    - name: LOGS_GENERATOR_LINES_TOTAL
      value: "600000"
    - name: LOGS_GENERATOR_DURATION
      value: 1m
```

After some time, you can see these lines in fluentd log

```
2000-01-01 00:00:00 +0000 [error]: fluentd main process died unexpectedly. restarting.
```

Here's the memory consumption plot

![screenshot from 2016-10-12 14 38 52](https://cloud.githubusercontent.com/assets/1756505/19310498/a47846bc-908a-11e6-86d1-782b0a17ec92.png)

And without this plugin (type null in match clauses in configuration) memory consumption does not exceed 60 MB, so the problem is not with fluentd pipeline.

![screenshot from 2016-10-12 15 19 25](https://cloud.githubusercontent.com/assets/1756505/19311612/6d0aacf6-908f-11e6-9d59-26d6ef683db7.png)
